name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check and create ECR repo if not exists
        run: |
          REPO_NAME="strapi-app-karthik"
          REGION="us-east-1"

          # Check if the repo exists
          aws ecr describe-repositories --repository-names "$REPO_NAME" --region $REGION > /dev/null 2>&1

          if [ $? -ne 0 ]; then
            echo "Repository $REPO_NAME does not exist. Creating it..."
            aws ecr create-repository --repository-name "$REPO_NAME" --region $REGION
          else
            echo "Repository $REPO_NAME already exists. Skipping creation."
          fi

      - name: Build, tag, and push Docker image
        working-directory: ./  # Build from root directory
        env:
          ECR_REGISTRY: 118273046134.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: strapi-app-karthik
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest