name: Strapi Terraform Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual trigger


env:
  ECR_REPOSITORY: strapi-app-karthik
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_URI: "118273046134.dkr.ecr.us-east-1.amazonaws.com/strapi-app-karthik:latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          118273046134.dkr.ecr.us-east-1.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -var="image_tag=latest"
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Apply
        working-directory: ./terraform
              
        run: |
          terraform apply -auto-approve -var="image_tag=latest"

        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Public IP
        working-directory: ./terraform
        id: ip
        run: |
          IP=$(terraform output -raw public_ip)
          echo "public_ip=$IP" >> $GITHUB_OUTPUT

      - name: Verify Deployment
        run: |
          echo "Verifying deployment at http://${{ steps.ip.outputs.public_ip }}:1337"
          curl --retry 5 --retry-delay 10 --retry-connrefused http://${{ steps.ip.outputs.public_ip }}:1337